version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: .
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ENV_FILE: .env.docker
      NODE_ENV: development
      MONGO_URI: mongodb://admin:password@mongodb:27017/maindb?authSource=admin
      JWT_SECRET: supersecretkey
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "npm install && node seed.js && npm run dev"]

  tests:
    build: .
    container_name: backend_test_container
    environment:
      NODE_ENV: test
      MONGO_URI_TEST: mongodb://admin:password@mongodb:27017/test?authSource=admin
      JWT_SECRET: supersecretkey
    depends_on:
      mongodb:
        condition: service_healthy
    command: ["sh", "-c", "npm install && npm run test"]

volumes:
  mongodb_data:
  mongodb_config:
